"""add object_type and object_id to security_logs

Revision ID: 729f7c9ff08f
Revises: ba6f49a3470e
Create Date: 2026-07-20 13:17:39.356932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729f7c9ff08f'
down_revision = 'ba6f49a3470e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_security_logs_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_object_type'), ['object_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_logs_object_type'))
        batch_op.drop_index(batch_op.f('ix_security_logs_object_id'))
        batch_op.drop_column('object_id')
        batch_op.drop_column('object_type')

    # ### end Alembic commands ###
