"""add_session_id_to_academic_models_and_is_legacy

Revision ID: 7c3aa78b5d7c
Revises: a1b2c3d4e5f6
Create Date: 2026-07-12 10:16:22.293866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c3aa78b5d7c'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_announcements_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(None, 'test_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(None, 'test_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comments_session_id'), ['session_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('comments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'forum_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'test_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_forum_posts_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(None, 'test_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_column('kategori')

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_legacy', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('session_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)

    # Flag existing legacy sessions in DB
    op.execute("UPDATE test_sessions SET is_legacy = 1 WHERE session_name LIKE '%Legacy%'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.alter_column('session_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('is_legacy')

    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_forum_posts_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_ibfk_1'), 'forum_posts', ['post_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_comments_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_announcements_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
