"""Add submission_id column to security_logs

Revision ID: ba6f49a3470e
Revises: 7c3aa78b5d7c
Create Date: 2026-07-19 17:17:58.229734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6f49a3470e'
down_revision = '7c3aa78b5d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_column('submission_id')

    # ### end Alembic commands ###
